version: '3'
services:
  conduit:
    build: .
    image: mander77/devopstest:1.1
    environment:
      ASPNETCORE_Conduit_DatabaseProvider: "sqlserver"
      ASPNETCORE_Conduit_ConnectionString: "Server=db;Database=conduit;User Id=sa;Password=tEst@12345;"
    ports:
     - "5000:5000"
    links:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-CU10-ubuntu-20.04
    restart: always
    environment:
      ACCEPT_EULA: "true"
      SA_PASSWORD: "tEst@12345"
      MSSQL_PID: "Developer"