name: ci

on: [push]

jobs:
  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker Image
        id: docker_build
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devopstest:latest .
      - name: Push Docker Image
        id: docker_push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker image push ${{ secrets.DOCKERHUB_USERNAME }}/devopstest:latest

  helm:
    name: Deploy to Kubernetes
    needs: docker
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: app
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: 'v1.19.0'
          kubernetes version: 'v1.21.0'
          github token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy Helm Chart
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm install conduit-api .\conduit-deploy\ --wait --namespace=default
